### ISSUE TITLE
warning about length of block name

### ISSUE THREAD

**Issue by danmarsden** [kepeter/moodle-block_knowledge_sharing#1]
Moodle requires table names to be less than 28 characters - if in future you make changes to your plugin and want to add some database tables to your plugin you may have difficulty because the table names start with the frankenstyle plugin name eg:
block_knowledge_sharing_mytable.

this means that your table "names will need to be 4 characters or less eg:
block_knowledge_sharing_tab1

once a plugin is released in the plugins db - it can be quite hard to rename (you have to release a new plugin) 

This is just something for you to consider - it doesn't block approval in the plugins db, but let us know if you decide to change the name prior to approval.

**Comment by kepeter** [comment]
I see. But I do not want tables here only settings...
So I close it for this plugin and try to remember for possibly future ones...
