### ISSUE TITLE
functions must be namespaced or use frankenstlye prefix

### ISSUE THREAD

**Issue by danmarsden** [kepeter/moodle-block_knowledge_sharing#2]
locallib.php defines the following functions:
_tree_by_tag()
load_knowledge_tree
load_knowledge_tree_for_tag

these should be more like this:
block_knowledge_sharing_tree_by_tag()
block_knowledge_sharing_load_knowledge_tree()
block_knowledge_sharing_load_knowledge_tree_for_tag()

functions should use the frankenstyle prefix to make sure you don't clash with other functions in the core code base (which may get added in future) or other plugins on the site.

**Comment by kepeter** [comment]
Did it...

Commits:

- 449a387c201fd6cae82a9da1294a66ae8b193034
- f29fc12a49ee7940bc4a54c5c317911ccfed93c9
- 4a7a8ffa3e85db8cdaac14cb9c3ac2ec6456d81d
