### ISSUE TITLE
php debug warnings when viewing a course with the block.

### ISSUE THREAD

**Issue by danmarsden** [kepeter/moodle-block_knowledge_sharing#4]
Warning:  explode() expects parameter 2 to be string, array given in /moodle/blocks/knowledge_sharing/locallib.php on line 51

Notice:  Trying to get property 'type' of non-object in /moodle/blocks/knowledge_sharing/renderer.php on line 148

Notice:  Trying to get property 'type' of non-object in /moodle/blocks/knowledge_sharing/renderer.php on line 155

Notice:  Trying to get property 'type' of non-object in /moodle/blocks/knowledge_sharing/renderer.php on line 164

Notice:  Trying to get property 'type' of non-object in /moodle/blocks/knowledge_sharing/renderer.php on line 173

Notice:  Trying to get property 'type' of non-object in /moodle/blocks/knowledge_sharing/renderer.php on line 181

**Comment by kepeter** [comment]
I do not see these errors...
I did turn on MOODLE debug messages, but still nothing...
What I have to tun on for them?

**Comment by kepeter** [comment]
Found them...
Fixed in commit 1c348f90ae4552ebde1e92ffb5c0df403b651efd
