### ISSUE TITLE
drag/drop fails when you drag to bottom of a list in a a section

### ISSUE THREAD

**Issue by danmarsden** [kepeter/moodle-block_knowledge_sharing#5]
When you try to drag an activity and put it at the "bottom" of the existing section - seems to be potential conflict with other drag/drop code and the "add files here" flicks on/off when holding down the mouse button, releasing the mouse button fails to add the activity.

You need to hover over the title of the section or in a place the drag/drop for files doesn't activate for it to work as expected.

I'm not sure if this occurs in older releases (I was testing in the master Moodle branch) - If you can't fix this easily but don't want it to block approval in the plugins db you could update the plugins db description and readme to document this behaviour and explain the workaround.

**Comment by kepeter** [comment]
Both flickering and failure fixed (were connected)...
Commit: 31c693efb93fe6802cdc8d1aab28ab0eb7fb8f85
