### ISSUE TITLE
Access control /capability checks missing

### ISSUE THREAD

**Issue by danmarsden** [kepeter/moodle-block_knowledge_sharing#7]
I couldn't see any evidence of capability checking in the code that builds the tree to make sure the current user should be able to see the course content within the knowledge tree - there should be some level of capability checking in your webservice and in the code that builds the tree to make sure the user can see the course/content - maybe by using something like:
require_capability('moodle/course:manageactivities', $modcontext);

Like the course/mod.php does when using duplicate_module()

Otherwise - anyone logged in could potentially trigger your services to duplicate content they should not have access to.

**Comment by danmarsden** [comment]
yeah - those are all just data retrieval functions - they expect that you have already checked to see if the user should be able to access the course/category/content you are getting.

course/mod.php does this per-module at the module context level.

**Comment by kepeter** [comment]
Added check for 'moodle/course:manageactivities' on module level...
Removing modules from the tree if there is no...
Hopefully it is the right path (I have to learn a lot of about the capability system of MOODLE)...
Commit 13f6f5483d8feacaf05943461cdce2aae69a33c6

**Comment by danmarsden** [comment]
that looks close and deals with the "display" of content - problem is you also need to do this on the "action" 

It would be possible for someone to modify parameters of a post call and get your ajax stuff to trigger the "duplicate" function. So you need to also add a similar has_capability check - probably somewhere around this line:
https://github.com/kepeter/moodle-block_knowledge_sharing/blob/master/classes/external.php#L53

**Comment by kepeter** [comment]
Done as suggested...
Commit 8d520c47eefe6c1ddf9be6893ad6c7671d664ca7
